### ISSUE TITLE
Issueベースの開発　レビュー依頼

### ISSUE THREAD

**Issue by nokanoka25** [nokanoka25/First-production#41]
■Webアプリの概要
グループキャンプ計画アプリです。グループでキャンプギアを共有し、重複荷物、不足荷物を確認し最適化できます。キャンプ場候補投票やリアルタイムチャットをこのアプリに一本化することで、共有内容が錯乱することを防ぎます。

使用想定

・ユーザー登録
・ログイン後マイページで持っているキャンプギアを登録
・キャンプグループを作成
・一緒に行くメンバーを招待、メンバーリクエストを承認。
・メンバーのキャンプギアを確認し、自分のキャンプギアと照らし合わせて重複しているギア　や必要ないギアを削除。
・全体のキャンプギアが確定したら車を何台手配するか、キャンプ場をどこにするかチャットやキャンプ場候補投票機　　能を使ってキャンプ場。車を手配し基本情報を更新する。
・キャンプ場での過ごし方や、行くまでのイベントや、帰りの予定を更新する。
・グループのMyGearを確認し自分の持ち物チェックとして使用する。

■1週間辺りの開発に向けられる時間
- 1週間あたり：30時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
https://github.com/users/nokanoka25/projects/1/views/1

■MVPリリースまで
[✔] ユーザー登録機能
[✔] ログイン機能
[✔] パスワード変更機能
[✔] メールアドレス変更機能
[✔] マイページ機能
[✔] キャンプ場候補投票機能
[✔] 持ち物登録、共有機能
[✔] チャット機能
[✔] 予定機能
[✔] グループ招待機能
■MVP後
- [✔] LINE招待機能
- [✔] Line通知機能

■MVPレビュー依頼予定日
予定日：2024年 12月 17日

**Comment by TakenakaEri** [comment]
綺麗に作成できていますね！LGMTです！
